// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StockAnalysis.Api.Data;

#nullable disable

namespace StockAnalysis.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StockAnalysis.Api.Data.BacktestJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CancelRequested")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProgressJson")
                        .HasColumnType("text");

                    b.Property<string>("ResultJson")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("BacktestJobs");
                });

            modelBuilder.Entity("StockAnalysis.Api.Models.Strategy.LiveSignal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ActualExitPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ActualRR")
                        .HasColumnType("numeric");

                    b.Property<bool>("BreakevenActivated")
                        .HasColumnType("boolean");

                    b.Property<decimal>("CurrentStop")
                        .HasColumnType("numeric");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("EntryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExitStrategy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("OutcomeTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SignalType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Stop")
                        .HasColumnType("numeric");

                    b.Property<Guid>("StrategyRuleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Target")
                        .HasColumnType("numeric");

                    b.Property<string>("TimeframeLabel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StrategyRuleId");

                    b.HasIndex("Symbol", "Status");

                    b.ToTable("LiveSignals");
                });

            modelBuilder.Entity("StockAnalysis.Api.Models.Strategy.Strategy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Strategies");
                });

            modelBuilder.Entity("StockAnalysis.Api.Models.Strategy.StrategyRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BiasTimeframe")
                        .HasColumnType("text");

                    b.Property<string>("ConfirmTimeframe")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExitStrategy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("FixedRRatio")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("KillZoneOnly")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SignalTimeframe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SignalTypesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StrategyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan?>("TradingWindowEnd")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("TradingWindowStart")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("StrategyId");

                    b.ToTable("StrategyRules");
                });

            modelBuilder.Entity("StockAnalysis.Api.Models.Strategy.LiveSignal", b =>
                {
                    b.HasOne("StockAnalysis.Api.Models.Strategy.StrategyRule", "Rule")
                        .WithMany("Signals")
                        .HasForeignKey("StrategyRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("StockAnalysis.Api.Models.Strategy.StrategyRule", b =>
                {
                    b.HasOne("StockAnalysis.Api.Models.Strategy.Strategy", "Strategy")
                        .WithMany("Rules")
                        .HasForeignKey("StrategyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Strategy");
                });

            modelBuilder.Entity("StockAnalysis.Api.Models.Strategy.Strategy", b =>
                {
                    b.Navigation("Rules");
                });

            modelBuilder.Entity("StockAnalysis.Api.Models.Strategy.StrategyRule", b =>
                {
                    b.Navigation("Signals");
                });
#pragma warning restore 612, 618
        }
    }
}
